package relatorio;

import conecta.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import model.Hospede;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.ArrayList;


/**
 * @author kelwin_santos
 */
public class RelatorioHospede extends javax.swing.JInternalFrame {

     Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    ArrayList<Hospede> lista = new ArrayList<>();
    
    /**
     * Creates new form RelatorioHospede
     */
    public RelatorioHospede() {
        initComponents();
        
        conexao = Conexao.conector();

        tabelaHospede.setRowHeight(30);
        setTable();
        listarHospede();
        
    }
    
    public ArrayList<Hospede> consultaHospede() {
        String sql = "select * from tb_hospedes";

        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                Hospede hospede = new Hospede();
                hospede.setId_hospede(rs.getInt("id_hospede"));
                hospede.setTxtNome(rs.getString("txtNome"));
                hospede.setTxtCpf(rs.getString("txtCpf"));
                hospede.setTxtFone(rs.getString("txtFone"));
                hospede.setTxtEmail(rs.getString("txtEmail"));
                
                lista.add(hospede);

            }

        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Consultar Hóspedes" + erro);
        }

        return lista;

    }

    private void setTable() {

        tabelaHospede.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
       
    }

    private void listarHospede() {
        try {

             
            DefaultTableModel model = (DefaultTableModel) tabelaHospede.getModel();
            model.setNumRows(0);
            ArrayList<Hospede> lista = consultaHospede();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId_hospede(),
                    lista.get(num).getTxtNome(),
                    lista.get(num).getTxtCpf(),
                    lista.get(num).getTxtFone(),
                    lista.get(num).getTxtEmail()
                    
                });
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Listar Hóspedes" + erro);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaHospede = new javax.swing.JTable();

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        setClosable(true);
        setPreferredSize(new java.awt.Dimension(630, 550));

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(630, 30));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DoisBoneco_20x20.png"))); // NOI18N
        jLabel1.setText("RELATÓRIO DE HÓSPEDES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        tabelaHospede.setBackground(new java.awt.Color(51, 51, 51));
        tabelaHospede.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tabelaHospede.setForeground(new java.awt.Color(255, 255, 255));
        tabelaHospede.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "CPF", "TELEFONE", "E-MAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaHospede.setSelectionBackground(new java.awt.Color(102, 0, 0));
        jScrollPane1.setViewportView(tabelaHospede);
        if (tabelaHospede.getColumnModel().getColumnCount() > 0) {
            tabelaHospede.getColumnModel().getColumn(0).setResizable(false);
            tabelaHospede.getColumnModel().getColumn(0).setPreferredWidth(25);
            tabelaHospede.getColumnModel().getColumn(1).setResizable(false);
            tabelaHospede.getColumnModel().getColumn(1).setPreferredWidth(150);
            tabelaHospede.getColumnModel().getColumn(2).setResizable(false);
            tabelaHospede.getColumnModel().getColumn(2).setPreferredWidth(100);
            tabelaHospede.getColumnModel().getColumn(3).setResizable(false);
            tabelaHospede.getColumnModel().getColumn(3).setPreferredWidth(100);
            tabelaHospede.getColumnModel().getColumn(4).setResizable(false);
            tabelaHospede.getColumnModel().getColumn(4).setPreferredWidth(200);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaHospede;
    // End of variables declaration//GEN-END:variables
}
