/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import conecta.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import consulta.ConsultaFuncionario;
import consulta.ConsultaProduto;
import consulta.ConsultaQuartos;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import javax.swing.Timer;
import reservas.Hospedar;
import relatorio.RelatorioHospede;

/**
 * @author Acer
 */
public class Home extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Home
     */
    //=============== PERMITE MAXIMIZAR A JANELA =================
    public Home() {
        initComponents();

        setExtendedState(MAXIMIZED_BOTH);

        conexao = Conexao.conector();

        nome_usuario.setText(TelaLogin.nm_user);
        
        Timer timer = new Timer(1000, new hora());
timer.start();
        
    }

    void funcionariologado() {

        String sql = "select login from funcionario as f/n"
                + "inner join log as l on f.idfuncionario = l.idfuncionario"
                + "where l.idlog = (select MAX (idlog) AS idlog from log)";

      ;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LogoWayz = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nome_usuario = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        lblHorario = new javax.swing.JLabel();
        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCad = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        menuFunCad = new javax.swing.JMenuItem();
        menuFunCon = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuQuartCad = new javax.swing.JMenuItem();
        menuQuartCon = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuProdCad = new javax.swing.JMenuItem();
        menuProdCon = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuResAdd = new javax.swing.JMenuItem();
        menuResCon = new javax.swing.JMenuItem();
        menuResFin = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuVendProd = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuRelHosp = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuOpFund = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Wayz - Home");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 0, 0, new java.awt.Color(0, 0, 0)));

        LogoWayz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoWayzSemNome (2).png"))); // NOI18N
        LogoWayz.setPreferredSize(new java.awt.Dimension(450, 450));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/account_avatar_face_man_people_profile_user_icon_123197 (1).png"))); // NOI18N

        nome_usuario.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        nome_usuario.setText("Usuário");

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogOut_15x15.png"))); // NOI18N
        btnLogout.setText("Logout ");
        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setOpaque(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jCalendar1.setBackground(new java.awt.Color(0, 0, 0));
        jCalendar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jCalendar1.setDecorationBackgroundColor(new java.awt.Color(255, 255, 255));
        jCalendar1.setDecorationBordersVisible(true);
        jCalendar1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jCalendar1.setOpaque(false);
        jCalendar1.setWeekOfYearVisible(false);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("CALENDÁRIO");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("HORÁRIO DE BRASÍLIA");

        lblHorario.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblHorario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHorario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(LogoWayz, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(108, 108, 108))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnLogout))
                    .addComponent(nome_usuario))
                .addGap(128, 128, 128))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nome_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LogoWayz, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Desktop.setLayout(new javax.swing.BoxLayout(Desktop, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 485, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(490, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuBar1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(0, 0, 2, 0));
        jMenuBar1.setName(""); // NOI18N
        jMenuBar1.setOpaque(false);

        menuCad.setBackground(new java.awt.Color(255, 0, 0));
        menuCad.setBorder(null);
        menuCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cadastrar_25x25.png"))); // NOI18N
        menuCad.setText("Cadastros   |");
        menuCad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCad.setFocusable(false);
        menuCad.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        jMenu5.setBackground(new java.awt.Color(255, 255, 255));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Funcionarios_20x20.png"))); // NOI18N
        jMenu5.setText("Funcionários");
        jMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu5.setFocusable(false);
        jMenu5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jMenu5.setOpaque(true);
        jMenu5.setRequestFocusEnabled(false);

        menuFunCad.setBackground(new java.awt.Color(255, 255, 255));
        menuFunCad.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menuFunCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BonecoPlus_20x20.png"))); // NOI18N
        menuFunCad.setText("Cadastrar");
        menuFunCad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuFunCad.setOpaque(true);
        menuFunCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFunCadActionPerformed(evt);
            }
        });
        jMenu5.add(menuFunCad);

        menuFunCon.setBackground(new java.awt.Color(255, 255, 255));
        menuFunCon.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menuFunCon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa_20x20.png"))); // NOI18N
        menuFunCon.setText("Consultar");
        menuFunCon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuFunCon.setOpaque(true);
        menuFunCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFunConActionPerformed(evt);
            }
        });
        jMenu5.add(menuFunCon);

        menuCad.add(jMenu5);

        jMenu7.setBackground(new java.awt.Color(255, 255, 255));
        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Casa_20x20.png"))); // NOI18N
        jMenu7.setText("Quartos");
        jMenu7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu7.setFocusable(false);
        jMenu7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jMenu7.setOpaque(true);

        menuQuartCad.setBackground(new java.awt.Color(255, 255, 255));
        menuQuartCad.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menuQuartCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_plus_outline_icon_139461_20x20.png"))); // NOI18N
        menuQuartCad.setText("Cadastrar");
        menuQuartCad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuQuartCad.setOpaque(true);
        menuQuartCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuartCadActionPerformed(evt);
            }
        });
        jMenu7.add(menuQuartCad);

        menuQuartCon.setBackground(new java.awt.Color(255, 255, 255));
        menuQuartCon.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menuQuartCon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa_20x20.png"))); // NOI18N
        menuQuartCon.setText("Consultar");
        menuQuartCon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuQuartCon.setOpaque(true);
        menuQuartCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuartConActionPerformed(evt);
            }
        });
        jMenu7.add(menuQuartCon);

        menuCad.add(jMenu7);

        jMenu6.setBackground(new java.awt.Color(255, 255, 255));
        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ComprasICon_1_20x20.png"))); // NOI18N
        jMenu6.setText("Produtos");
        jMenu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jMenu6.setOpaque(true);

        menuProdCad.setBackground(new java.awt.Color(255, 255, 255));
        menuProdCad.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menuProdCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AdicionarCarrinho_20x20.png"))); // NOI18N
        menuProdCad.setText("Cadastrar");
        menuProdCad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuProdCad.setOpaque(true);
        menuProdCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdCadActionPerformed(evt);
            }
        });
        jMenu6.add(menuProdCad);

        menuProdCon.setBackground(new java.awt.Color(255, 255, 255));
        menuProdCon.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menuProdCon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa_20x20.png"))); // NOI18N
        menuProdCon.setText("Consultar");
        menuProdCon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuProdCon.setOpaque(true);
        menuProdCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdConActionPerformed(evt);
            }
        });
        jMenu6.add(menuProdCon);

        menuCad.add(jMenu6);

        jMenuBar1.add(menuCad);

        jMenu2.setBackground(new java.awt.Color(255, 0, 0));
        jMenu2.setBorder(null);
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Reserva_25x25.png"))); // NOI18N
        jMenu2.setText("Reservas   |");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        menuResAdd.setBackground(new java.awt.Color(255, 255, 255));
        menuResAdd.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menuResAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AdicionarReserva_20x20.png"))); // NOI18N
        menuResAdd.setText("Hospedar");
        menuResAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuResAdd.setOpaque(true);
        menuResAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuResAddActionPerformed(evt);
            }
        });
        jMenu2.add(menuResAdd);

        menuResCon.setBackground(new java.awt.Color(255, 255, 255));
        menuResCon.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menuResCon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ConsultarReserva_20x20.png"))); // NOI18N
        menuResCon.setText("Consultar");
        menuResCon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuResCon.setOpaque(true);
        menuResCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuResConActionPerformed(evt);
            }
        });
        jMenu2.add(menuResCon);

        menuResFin.setBackground(new java.awt.Color(255, 255, 255));
        menuResFin.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menuResFin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FinalizarReserva_20x20.png"))); // NOI18N
        menuResFin.setText("Finalizar");
        menuResFin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuResFin.setOpaque(true);
        jMenu2.add(menuResFin);

        jMenuBar1.add(jMenu2);

        jMenu1.setBackground(new java.awt.Color(255, 0, 0));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Carrinho_25x25.png"))); // NOI18N
        jMenu1.setText("Vendas   |");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        menuVendProd.setBackground(new java.awt.Color(255, 255, 255));
        menuVendProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cesta_produtos_20x20.png"))); // NOI18N
        menuVendProd.setText("Produtos");
        menuVendProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuVendProd.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menuVendProd.setOpaque(true);

        jMenuItem5.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Caixa_20x20.png"))); // NOI18N
        jMenuItem5.setText("Estoque");
        jMenuItem5.setOpaque(true);
        menuVendProd.add(jMenuItem5);

        jMenu1.add(menuVendProd);

        jMenuBar1.add(jMenu1);

        jMenu3.setBackground(new java.awt.Color(255, 0, 0));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/relatório_25x25.png"))); // NOI18N
        jMenu3.setText("Relatórios   |");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        menuRelHosp.setBackground(new java.awt.Color(255, 255, 255));
        menuRelHosp.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menuRelHosp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DoisBoneco_20x20.png"))); // NOI18N
        menuRelHosp.setText("Hóspedes");
        menuRelHosp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuRelHosp.setOpaque(true);
        menuRelHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelHospActionPerformed(evt);
            }
        });
        jMenu3.add(menuRelHosp);

        jMenuItem2.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Reserva_20x20.png"))); // NOI18N
        jMenuItem2.setText("Reservas");
        jMenuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem2.setOpaque(true);
        jMenu3.add(jMenuItem2);

        jMenuItem3.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CarrinhoComprado_20x20.png"))); // NOI18N
        jMenuItem3.setText("Vendas");
        jMenuItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem3.setOpaque(true);
        jMenu3.add(jMenuItem3);

        jMenuItem4.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Moeda_20x20.png"))); // NOI18N
        jMenuItem4.setText("Financeiro");
        jMenuItem4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem4.setOpaque(true);
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(255, 0, 0));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SettingsICon_25x25_1_20x20.png"))); // NOI18N
        jMenu4.setText("Configurações");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        menuOpFund.setBackground(new java.awt.Color(255, 255, 255));
        menuOpFund.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menuOpFund.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PlanoDeFundo_20x20.png"))); // NOI18N
        menuOpFund.setText("Plano de fundo");
        menuOpFund.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuOpFund.setOpaque(true);
        jMenu4.add(menuOpFund);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuFunCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFunCadActionPerformed

        CadastroFuncionario cadastro = new CadastroFuncionario();

        cadastro.setVisible(true);

        Desktop.add(cadastro);

    }//GEN-LAST:event_menuFunCadActionPerformed

    private void menuQuartCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuartCadActionPerformed

        CadastroQuartos cad_quarto = new CadastroQuartos();
        
        cad_quarto.setVisible(true);
        
        Desktop.add(cad_quarto);
        
    }//GEN-LAST:event_menuQuartCadActionPerformed

    private void menuQuartConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuartConActionPerformed
        
        ConsultaQuartos consulta_quarto = new ConsultaQuartos();
       
       consulta_quarto.setVisible(true);
       
       Desktop.add(consulta_quarto);
        
    }//GEN-LAST:event_menuQuartConActionPerformed

    private void menuResConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuResConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuResConActionPerformed

    private void menuResAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuResAddActionPerformed
       
        Hospedar hospedagem = new Hospedar();
       
       hospedagem.setVisible(true);
       
       Desktop.add(hospedagem);
        
        
    }//GEN-LAST:event_menuResAddActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        int logout = JOptionPane.showConfirmDialog(null, "Voltar a tela de login?", "Confirmação", JOptionPane.YES_NO_OPTION);

        int saida = 1;

        if (logout == JOptionPane.YES_OPTION) {

            if (saida > 0) {

                this.dispose();

                TelaLogin login = new TelaLogin();

                login.setVisible(true);
            }
        } else {
            saida = 0;
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void menuFunConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFunConActionPerformed

       ConsultaFuncionario consulta_fun = new ConsultaFuncionario();
       
       consulta_fun.setVisible(true);
       
       Desktop.add(consulta_fun);

    }//GEN-LAST:event_menuFunConActionPerformed

    private void menuProdCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdCadActionPerformed

       CadastroProduto cad_produto = new CadastroProduto();
       
       cad_produto.setVisible(true);
       
       Desktop.add(cad_produto);
        
    }//GEN-LAST:event_menuProdCadActionPerformed

    private void menuProdConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdConActionPerformed
       
        ConsultaProduto consulta_produto = new ConsultaProduto();
        
        consulta_produto.setVisible(true);
        
        Desktop.add(consulta_produto);
    }//GEN-LAST:event_menuProdConActionPerformed

    private void menuRelHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelHospActionPerformed
        
        RelatorioHospede relatorioHospede = new RelatorioHospede();
        
        relatorioHospede.setVisible(true);
        
        Desktop.add(relatorioHospede);
        
    }//GEN-LAST:event_menuRelHospActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JLabel LogoWayz;
    private javax.swing.JButton btnLogout;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JMenu menuCad;
    private javax.swing.JMenuItem menuFunCad;
    private javax.swing.JMenuItem menuFunCon;
    private javax.swing.JMenuItem menuOpFund;
    private javax.swing.JMenuItem menuProdCad;
    private javax.swing.JMenuItem menuProdCon;
    private javax.swing.JMenuItem menuQuartCad;
    private javax.swing.JMenuItem menuQuartCon;
    private javax.swing.JMenuItem menuRelHosp;
    private javax.swing.JMenuItem menuResAdd;
    private javax.swing.JMenuItem menuResCon;
    private javax.swing.JMenuItem menuResFin;
    private javax.swing.JMenu menuVendProd;
    private javax.swing.JLabel nome_usuario;
    // End of variables declaration//GEN-END:variables

class hora implements ActionListener{
    @Override
    
    public void actionPerformed(ActionEvent e) {
        Calendar now = Calendar.getInstance();
        lblHorario.setText(String.format("%1$tH:%1$tM", now));
    }
}

}
