/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author Acer
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCad = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        menuFunCad = new javax.swing.JMenuItem();
        menuFunCon = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuQuartCad = new javax.swing.JMenuItem();
        menuQuartCon = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuHosCad = new javax.swing.JMenuItem();
        menuHosCon = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        menuQuartDisp = new javax.swing.JMenuItem();
        menuQuartOcup = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Wayz - Home");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 0, 0));

        menuCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PapelCanetaIcone.png"))); // NOI18N
        menuCad.setText("Cadastros   |");
        menuCad.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/RegistrarBoneco_20x20.png"))); // NOI18N
        jMenu5.setText("Funcionários");
        jMenu5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        menuFunCad.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menuFunCad.setText("Cadastrar");
        menuFunCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFunCadActionPerformed(evt);
            }
        });
        jMenu5.add(menuFunCad);

        menuFunCon.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menuFunCon.setText("Consultar");
        jMenu5.add(menuFunCon);

        menuCad.add(jMenu5);

        jMenu6.setText("Quartos");
        jMenu6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        menuQuartCad.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menuQuartCad.setText("Cadastrar");
        jMenu6.add(menuQuartCad);

        menuQuartCon.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menuQuartCon.setText("Consultar");
        menuQuartCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuartConActionPerformed(evt);
            }
        });
        jMenu6.add(menuQuartCon);

        menuCad.add(jMenu6);

        jMenu7.setText("Hóspedes");
        jMenu7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        menuHosCad.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menuHosCad.setText("Cadastrar");
        menuHosCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHosCadActionPerformed(evt);
            }
        });
        jMenu7.add(menuHosCad);

        menuHosCon.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menuHosCon.setText("Consultar");
        menuHosCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHosConActionPerformed(evt);
            }
        });
        jMenu7.add(menuHosCon);

        menuCad.add(jMenu7);

        jMenuBar1.add(menuCad);

        jMenu2.setText("Reservas   |");
        jMenu2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        jMenu8.setText("Quartos");
        jMenu8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        menuQuartDisp.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menuQuartDisp.setText("Quartos disponíveis");
        menuQuartDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuartDispActionPerformed(evt);
            }
        });
        jMenu8.add(menuQuartDisp);

        menuQuartOcup.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        menuQuartOcup.setText("Quartos ocupados");
        jMenu8.add(menuQuartOcup);

        jMenu2.add(jMenu8);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Venda de produtos   |");
        jMenu1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Relatórios   |");
        jMenu3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Configurações");
        jMenu4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuFunCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFunCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFunCadActionPerformed

    private void menuQuartConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuartConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuQuartConActionPerformed

    private void menuHosCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHosCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHosCadActionPerformed

    private void menuHosConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHosConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHosConActionPerformed

    private void menuQuartDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuartDispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuQuartDispActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuCad;
    private javax.swing.JMenuItem menuFunCad;
    private javax.swing.JMenuItem menuFunCon;
    private javax.swing.JMenuItem menuHosCad;
    private javax.swing.JMenuItem menuHosCon;
    private javax.swing.JMenuItem menuQuartCad;
    private javax.swing.JMenuItem menuQuartCon;
    private javax.swing.JMenuItem menuQuartDisp;
    private javax.swing.JMenuItem menuQuartOcup;
    // End of variables declaration//GEN-END:variables
}
